# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Dataframe

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ColumnDataHolder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ColumnDataHolder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsColumnDataHolder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ColumnDataHolder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColumnDataHolder
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ColumnDataHolder
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ColumnDataHolderStart(builder):
    builder.StartObject(2)

def Start(builder):
    ColumnDataHolderStart(builder)

def ColumnDataHolderAddDataType(builder, dataType):
    builder.PrependUint8Slot(0, dataType, 0)

def AddDataType(builder, dataType):
    ColumnDataHolderAddDataType(builder, dataType)

def ColumnDataHolderAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    ColumnDataHolderAddData(builder, data)

def ColumnDataHolderEnd(builder):
    return builder.EndObject()

def End(builder):
    return ColumnDataHolderEnd(builder)
