# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Dataframe

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ColumnMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ColumnMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsColumnMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ColumnMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColumnMetadata
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ColumnMetadata
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ColumnMetadataStart(builder):
    builder.StartObject(2)

def Start(builder):
    ColumnMetadataStart(builder)

def ColumnMetadataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ColumnMetadataAddName(builder, name)

def ColumnMetadataAddType(builder, type):
    builder.PrependInt8Slot(1, type, 0)

def AddType(builder, type):
    ColumnMetadataAddType(builder, type)

def ColumnMetadataEnd(builder):
    return builder.EndObject()

def End(builder):
    return ColumnMetadataEnd(builder)
