# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Dataframe

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Int64Column(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Int64Column()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInt64Column(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Int64Column
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Int64Column
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Int64Column
    def ValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # Int64Column
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Int64Column
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Int64ColumnStart(builder):
    builder.StartObject(1)

def Start(builder):
    Int64ColumnStart(builder)

def Int64ColumnAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def AddValues(builder, values):
    Int64ColumnAddValues(builder, values)

def Int64ColumnStartValuesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartValuesVector(builder, numElems):
    return Int64ColumnStartValuesVector(builder, numElems)

def Int64ColumnEnd(builder):
    return builder.EndObject()

def End(builder):
    return Int64ColumnEnd(builder)
